[build]
  command = "npm run build:netlify"
  publish = ".next"
  base = ""

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20.18.0"
  NPM_FLAGS = "--legacy-peer-deps"
  # Fallback values for missing Sanity config
  NEXT_PUBLIC_SANITY_PROJECT_ID = "placeholder-project-id"
  NEXT_PUBLIC_SANITY_DATASET = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Handle Next.js Image Optimization
[[redirects]]
  from = "/_next/image"
  to = "/_next/image"
  status = 200

[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  force = true
  headers = {Cache-Control = "public, max-age=31536000, immutable"}